### ISSUE TITLE
README

### ISSUE THREAD

**Issue by cyrus-** [hazelgrove/hazelnut-dynamics-agda#15]
for the benefit of the reviewers, we should have a brief overview of how to dive into the repo

**Comment by ivoysey** [comment]
Absolutely. I'm going to ignore this for a little while, though; with the POPL paper, I wrote a README and then had to rewrite it several times after refactoring something, which was kind of a waste of time.

**Comment by cyrus-** [comment]
yeah that's fine, just need to do it before submitting
