### ISSUE TITLE
break complete preservation down into complete expansion and complete preservation

### ISSUE THREAD

**Issue by cyrus-** [hazelgrove/hazelnut-dynamics-agda#21]
https://github.com/hazelgrove/hazelnut-dynamics-agda/blob/32b120343c0d195202ba718fd63f9c9eb7f63420/complete-preservation.agda#L19

see PDF -- make sure you have the "d' complete" premise on complete preservation

**Comment by ivoysey** [comment]
This whole connected component seems like a pretty substantial refactoring of the ideas involved here? Previously I don't think we ever talked about `d`s being complete, only `e`s in the same way as the POPL work (i.e. https://github.com/hazelgrove/hazelnut-dynamics-agda/blob/master/core.agda#L127)

**Comment by cyrus-** [comment]
yeah I don't think what we have before really made sense -- it only said anything about the very first step after expansion. we want to talk about the whole trace through evaluation of complete expressions

**Comment by cyrus-** [comment]
or if what we had before did make sense it would have required these new things as lemmas anyway

**Comment by ivoysey** [comment]
Do you want to keep what we had before and see if that's true? It feels a little higher level because it relates something in the source language into a property about how it steps.

**Comment by cyrus-** [comment]
sure. it should just be the composition of these three things.

**Comment by ivoysey** [comment]
cool.
