### ISSUE TITLE
double check quantification on all non-equality premises

### ISSUE THREAD

**Issue by ivoysey** [hazelgrove/hazelnut-dynamics-agda#26]

**Comment by ivoysey** [comment]
OK, @cyrus- : I think I have it right now, but the rules that mention ≠ are: EASubsume, BVArrCast, IAp, ICastArr, ICastHoleGround, ITExpand, CECastFinal. Could you double check that those are right in the current version and reply back here?

**Comment by ivoysey** [comment]
(FWIW just that diff won't actually suffice to check all of them because there were some I didn't change)

**Comment by cyrus-** [comment]
yup those all look correct to me
