### ISSUE TITLE
phrasing: dynamic -> internal expressions

### ISSUE THREAD

**Issue by cyrus-** [hazelgrove/hazelnut-dynamics-agda#41]
If "dynamic expression" appears in comments somewhere, change to "internal expression".

The sort name in the paper for the metavariable "d" is "IHExp" now. (I'm leaving the metavariable as "d" though)

**Comment by ivoysey** [comment]
@cyrus- should I go so far as to change the name of the types, too? Right now it's `hexp` and `dhexp` not like `eexp` and `iexp`.
