### ISSUE TITLE
alternative formulation of DCCast

### ISSUE THREAD

**Issue by cyrus-** [hazelgrove/hazelnut-dynamics-agda#43]
right now, we have that tau_1 and tau_2 are complete, but it's maybe more informative to require that they be equal (this is implied by typing and the properties of type consistency for well-typed internal expressions)

(don't bother with this before the deadline, just noting it down for posterity)

**Comment by ivoysey** [comment]
that sounds like something that should probably be a theorem, not baked into the rules. the rules are the homomorphism on the structure; that seems like a consequence.

**Comment by ivoysey** [comment]
_editing the issue name to match the rule name; it's DCCast, not DCastComplete_

**Comment by ivoysey** [comment]
I proved something similar too, @cyrus- : https://github.com/hazelgrove/hazelnut-dynamics-agda/blob/master/complete-progress.agda#L35
