### ISSUE TITLE
prove progress checks: errors don't step

### ISSUE THREAD

**Issue by ivoysey** [hazelgrove/hazelnut-dynamics-agda#5]
```
  -- errors and expressions that step are disjoint                                                                                                                                   
  es : ∀{d Δ} → Δ ⊢ d err → (Σ[ d' ∈ dhexp ] (Δ ⊢ d ↦ d')) → ⊥
```

**Comment by cyrus-** [comment]
Did you find any ambiguous cases yet?

**Comment by ivoysey** [comment]
@cyrus- Two of them, I think, in the most recent version I just pushed. If you have any thoughts, I'd be interested to hear 'em. These could be errors in the rules.

The first is at [94](https://github.com/hazelgrove/hazelnut-dynamics-agda/blob/master/progress-checks.agda#L94). This is the case where the error is in a cast and both eval contexts are propagating through that cast.

```
Goal: ⊥
————————————————————————————————————————————————————————————
x₄   : .d == .ε ⟦ .d0' ⟧
x₃   : .Δ ⊢ .d0 →> .d0'
x₂   : .d₁ == .ε ⟦ .d0 ⟧
x₁   : .τ ~̸ .τ2
x    : .Δ , ∅ ⊢ .d₁ :: .τ2
.τ2  : htyp
.Δ   : Nat → Maybe ((htyp ctx) × htyp)
.d0  : dhexp
.d₁  : dhexp
.d0' : dhexp
.d   : dhexp
.ε   : ectx
.τ   : htyp
```

The second is at [107](https://github.com/hazelgrove/hazelnut-dynamics-agda/blob/master/progress-checks.agda#L107). This is the case where the error is in the second argument of an application site and both eval contexts are propagating through that branch of the application. 

```
Goal: ⊥
————————————————————————————————————————————————————————————
x₂   : .d1 == .ε ⟦ .d0' ⟧
x₁   : .Δ ⊢ .d0 →> .d0'
x    : .d3 == .ε ⟦ .d0 ⟧
er   : .Δ ⊢ .d2 err
.Δ   : Nat → Maybe ((htyp ctx) × htyp)
.d0  : dhexp
.d3  : dhexp
.d0' : dhexp
.d1  : dhexp
.d2  : dhexp
.ε   : ectx
```

**Comment by ivoysey** [comment]
I should point out that the second one looks a little bit like a recursive call / IH application but it doesn't quite workout because we know d2 is and error, not d1. So you can fill the hole with `es er (_ , (Step { }1 x₁ x₂))` and then get this goal, but there's no way to prove that.
```
Goal: .d2 == .ε ⟦ .d0 ⟧
————————————————————————————————————————————————————————————
x₂   : .d1 == .ε ⟦ .d0' ⟧
x₁   : .Δ ⊢ .d0 →> .d0'
x    : .d3 == .ε ⟦ .d0 ⟧
er   : .Δ ⊢ .d2 err
.Δ   : Nat → Maybe ((htyp ctx) × htyp)
.d0  : dhexp
.d3  : dhexp
.d0' : dhexp
.d1  : dhexp
.d2  : dhexp
.ε   : ectx
```

**Comment by ivoysey** [comment]
closing this, since the progress checks now have a different form post-rewrite; i'll open a new issue to replace it
