### ISSUE TITLE
rename "expansion" to "elaboration"

### ISSUE THREAD

**Issue by cyrus-** [hazelgrove/hazelnut-dynamics-agda#51]
going to do that in the final paper as well

**Comment by ivoysey** [comment]
@cyrus- you should make an issue over there, too, probably

**Comment by cyrus-** [comment]
done. since I guess the AE reviewers will be using the submitted paper, make a note in the README about the renaming too

**Comment by ivoysey** [comment]
so should i not rename it until after we change the paper? like if AE is going against the submitted paper, the agda should match that. and then we can change it for camera-ready and update the repo

**Comment by cyrus-** [comment]
ah yeah I guess the submission of the artifact will coincide with the final submission, not necessarily exactly the code that is reviewed for AE. so yeah, leave it for now and rename it later.
