### ISSUE TITLE
prove complete preservation

### ISSUE THREAD

**Issue by ivoysey** [hazelgrove/hazelnut-dynamics-agda#7]
```
  complete-preservation : {Δ : hctx} {e : hexp} {d d' : dhexp} {τ : htyp} →
             ecomplete e →
             ∅ ⊢ e ⇒ τ ~> d ⊣ Δ →
             Δ ⊢ d ↦ d' →
             Δ , ∅ ⊢ d' :: τ
```
@cyrus- said one or both of these was trivial and should be removed but i forget which one

**Comment by cyrus-** [comment]
I think this one is trivial? No need to remove it though, just prove it.

**Comment by ivoysey** [comment]
OK, yeah. I'll add full preservation as a postulate until I finish it so that I can confirm it's as we think. (Agda doesn't let you import modules that have holes in them, which is probably a good idea, and I already have the muscle memory of `grep postulate` before considering something to be finished.)
